name: default-environment
channels:
  - emscripten-forge
  - conda-forge
dependencies:
  # A Jupyter kernel for Python
  - xeus-python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-image
  - pillow
  - matplotlib
  - seaborn
  - pandas-datareader
  - netcdf4